services:
  vault:
    image: hashicorp/vault:1.15
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "token"

  # docker exec lade-passbolt-1 su -s /bin/bash -c "./bin/cake passbolt register_user -u test@test.com -f test -l test -r admin" www-data
  passbolt:
    image: passbolt/passbolt:latest-ce
    ports:
      - "8000:80"
    environment:
      APP_FULL_BASE_URL: http://localhost:8000
      DATASOURCES_DEFAULT_DRIVER: Cake\Database\Driver\Postgres
      DATASOURCES_DEFAULT_ENCODING: "utf8"
      DATASOURCES_DEFAULT_URL: "postgres://lade:lade@postgres:5432/lade?schema=passbolt"

  infisical:
    image: infisical/infisical:latest-postgres
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - SITE_URL=http://localhost:4000
      - ENCRYPTION_KEY=6c1fe4e407b8911c104518103505b218
      - AUTH_SECRET=5lrMXKKWCVocS/uerPsl7V+TX/aaUaI7iDkgl3tSmLE=
      - DB_CONNECTION_URI=postgres://lade:lade@postgres:5432/lade?schema=infisical
      - REDIS_URL=redis://redis:6379
    command: >-
      /bin/sh -c "
        npm run migration:latest &&
        ./standalone-entrypoint.sh
      "

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=lade
      - POSTGRES_USER=lade
      - POSTGRES_DB=lade

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
