Output resolution.gif
Output resolution.txt
Source settings.tape

Hide
Set TypingSpeed 0
Type "./cat-lade.yml token"
Enter
Type 'eval "$(lade on)"'
Enter
Set TypingSpeed 75ms
Sleep 2s
Show
Sleep 1s

Type 'echo token $TOKEN'
Enter
Sleep 4s

Hide
Set TypingSpeed 0
Type "./cat-lade.yml format"
Enter
Set TypingSpeed 75ms
Sleep 2s
Show
Sleep 1s

Type 'lade eval "file://../sources/config.json?query=.format"'
Enter
Sleep 4s
