Output resolution.gif
Output resolution.txt
Source settings.tape

Hide
Set TypingSpeed 0
Type 'eval "$(lade on)"'
Enter
Type "clear"
Enter
Type "./cat-lade.yml token"
Enter
Set TypingSpeed 75ms
Sleep 2s
Show
Sleep 1s

Type 'echo token $TOKEN'
Enter
Sleep 4s

Hide
Set TypingSpeed 0
Type "clear"
Enter
Type "./cat-lade.yml format"
Enter
Set TypingSpeed 75ms
Sleep 2s
Show
Sleep 1s

Type 'printenv FROM_FILE'
Enter
Sleep 4s
