apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lade-k3d-shared
servers: 1
agents: 0
kubeAPI:
  host: 127.0.0.1
  hostIP: 127.0.0.1
  hostPort: "6445"
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
